### ISSUE TITLE
Add kafka-node as pre-installed package in the Node.js version 8 environment

### ISSUE THREAD

**Issue by grudir** [ibm-functions/runtime-nodejs#169]
The pre-installed packages in the Node.js version 8 environment cover various widely used technologies. Since Kafka is a very popular streaming platform used in many SaaS offerings I request [kafka-node](https://www.npmjs.com/package/kafka-node) to be added to the preinstalled packages in the Node.js version 8 environment.

**Comment by csantanapr** [comment]
Hi @grudir at the moment we don't include a kafka client library, as the kafka API is better to be use from a persistent connection with a low amount of socket open interactions. In serverless/faas environments your functions will be creating too many open sockets to the kafka API affecting performance for your application but also easily hitting rate limits impose by the vendor such as IBM Cloud Event Stream service for many and fast sockets are allowed from a client to the broker

So the recommendation is to use the [Kafka API](https://console.bluemix.net/docs/services/EventStreams/eventstreams087.html#choose_api) with persistent connection using a microservice/server _It offers lower latency and higher throughput than the other APIs._,
