### ISSUE TITLE
Add xlsx as pre-installed package in the Node.js version 8 environment

### ISSUE THREAD

**Issue by grudir** [ibm-functions/runtime-nodejs#170]
Add [xlsx](https://www.npmjs.com/package/xlsx) as pre-installed package in the Node.js version 8 environment in order to provide utilities for building Excel spreadsheets.

**Comment by csantanapr** [comment]
Hi @grudir can you say why xlsx is better or the best package to alternatives? like [exceljs](https://www.npmjs.com/package/exceljs) and [excel4node](https://www.npmjs.com/package/excel4node)

Also are you a current IBM Cloud Functions customer currently using this library in your IBM Cloud Functions and packaging your self?

**Comment by grudir** [comment]
Hi @csantanapr 
xlsx is the most popular feature rich Node.js library for building Excel spreadsheets.

I'm part of the development team of IBM Watson Supply Chain Insights product. We are using IBM FaaS indirectly via another IBM product.

**Comment by csantanapr** [comment]
@grudir the package `xlsx` is now available only on `nodejs:10` in add regions for IBM Cloud Functions. enjoy 🚀

**Comment by grudir** [comment]
Thank you @csantanapr for the update!
