### ISSUE TITLE
Supprt MongoDB V4.2 by upgrading driver from 3.1.X to V3.3.4

### ISSUE THREAD

**Issue by HunderlineK** [ibm-functions/runtime-nodejs#194]
Hi, Databases for MongoDB on IBM Cloud supports mongo 4.2 as the preferred version:
https://cloud.ibm.com/catalog/services/databases-for-mongodb

However, MongoDB V4.2 requires a minimum driver version of 3.3.X:
https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility

So the current driver needs to be updated to ensure OOTB compatibility.

Thanks!

**Comment by falkzoll** [comment]
Thanks for mentioning this :-). 
I prepared a PR (PR #195) to update the mongodb package for the nodejs10 runtime to the current v3.3.4 version to also support mongo 4.2 databases.
I will get back here once it is complete.

**Comment by falkzoll** [comment]
The nodejs 10 runtime with the updated mongodb v3.3.4 is now active in the IBM Cloud :-).
Feel free to give it a try and to report issues in case you find some.
