### ISSUE TITLE
Add jsonwebtoken to out-of-the-box nodejs runtime environment.

### ISSUE THREAD

**Issue by arrraichu** [ibm-functions/runtime-nodejs#80]
[jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) is used to send data securely using the JSON Web Token open standard. It'd be nice to be able to use this npm package right out of the box, without webpacking the action every time.

**Comment by ScottChapman** [comment]
Looking for this too. Thanks!

**Comment by csantanapr** [comment]
Thanks @arrraichu sounds good to add
