### ISSUE TITLE
Add Libraries for Compose Databases

### ISSUE THREAD

**Issue by lornajane** [ibm-functions/runtime-nodejs#85]
We have excellent Cloudant support already but let's add the libraries to help get users quickly started with the Compose-for-* database offerings.  Here's what I think we need:

* **PostgreSQL** `pg` https://www.npmjs.com/package/pg
* **MySQL** `mysql` https://www.npmjs.com/package/mysql
* **MongoDB** `mongodb` https://www.npmjs.com/package/mongodb
* **Redis** `redis` https://www.npmjs.com/package/redis
* **RabbitMQ** `amqplib` https://www.npmjs.com/package/amqplib
* **Etcd** `etcd3` https://www.npmjs.com/package/etcd3
* **ElasticSearch** `elasticsearch` https://www.npmjs.com/package/elasticsearch
* **ScyllaDB**  `composeaddresstranslator` https://www.npmjs.com/package/composeaddresstranslator and `cassandra-driver` https://www.npmjs.com/package/cassandra-driver

**Comment by csantanapr** [comment]
Closed by #86
